version: "3"
services:
  controller-A-1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: controller-A-1
    container_name: controller-A-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-A-1:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_LISTENERS: "CONTROLLER://controller-A-1:29092"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      
  broker-A-1:
    image: confluentinc/cp-kafka:7.6.0
    hostname: broker-A-1
    container_name: broker-A-1
    depends_on:
      - controller-A-1
    ports:
      - "9095:9092"
      - "9104:9101"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_KRAFT_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-A-1:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-A-1:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://broker-A-1:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

  controller-B-1:
    image: confluentinc/cp-server:7.6.0
    hostname: controller-B-1
    container_name: controller-B-1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller"

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-B-1:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      CLUSTER_ID: "FgE08qayQ9yArkwhM4xriw"
      KAFKA_LISTENERS: "CONTROLLER://controller-B-1:29092"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      DEFAULT_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1

  broker-B-1:
    image: confluentinc/cp-server:7.6.0
    hostname: broker-B-1
    container_name: broker-B-1
    depends_on:
      - controller-B-1
    ports:
      - "19095:9092"
      - "19104:9101"
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: "broker"

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"

      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://broker-B-1:9092,PLAINTEXT_HOST://localhost:39092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@controller-B-1:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://broker-B-1:9092,PLAINTEXT_HOST://0.0.0.0:39092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      CLUSTER_ID: "FgE08qayQ9yArkwhM4xriw"

      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_TIER_METADATA_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

      CONFLUENT_CLUSTER_LINK_ENABLE: "true"
      CONFLUENT_CLUSTER_LINK_METADATA_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./config:/home/user

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    hostname: control-center
    container_name: control-center-cl
    depends_on:
      - broker-A-1
      - broker-B-1
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-A-1:9092'
      CONTROL_CENTER_KAFKA_DESTINATION-CLUSTER_BOOTSTRAP_SERVERS: 'broker-B-1:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021
